### ISSUE TITLE
преврашение кода в библиотеку

### ISSUE THREAD

**Issue by suguby** [IvanRyavkin/vovan#1]
Разбей код на функции - чтение данных, обработка, вывод результата. Сделай одну главную функцию main которая последовательно их вызывает. Сделай что бы main вызывался при прямом запуске скрипта (if __name__ == '__main__')

**Comment by IvanRyavkin** [comment]
создал ветку https://github.com/IvanRyavkin/vovan/tree/add_function

**Comment by suguby** [comment]
Отлично! но мы пока без веток, хорошо что ты это умеешь :) влей в мастер и дальше давай все в мастере.
По коду - функция get_data должна брать параметром имя файла, в main сделай что бы через sys.argv можно было передать имя файла (можно юзать argparse), если такового нет - выдавать usage.

**Comment by IvanRyavkin** [comment]
добавил argparse
Есть ощущение что try except излишне в функции create_parser, что скажете?

**Comment by IvanRyavkin** [comment]
up :)

**Comment by IvanRyavkin** [comment]
немного переделал, try except вынес в main так как в create_parser она ни к чему, create_parser теперь просто возвращает parser, в main получаем все namespace (удобно на будущее)
но от  try except как то не удалось избавится(((
+ два раза os.path.isfile(file_name) is False: мозолит глаз
что скажите?

**Comment by suguby** [comment]
да, так лучше. про os.path.isfile(file_name) is False - кмк лучше заюзать os.path.exists вначале.
насчет ввода правильного имени файла - не парься, не файл - выводи ошибку и завершай, иначе твой скрипт нельзя будет использовать в других скриптах.
и давай перейдем к след шагу - как доделаешь, закрывай issue

**Comment by IvanRyavkin** [comment]
переделал, закрываю, следующий шаг ООП, что посмотреть? какие указания?
