### ISSUE TITLE
Использование ООП-подхода

### ISSUE THREAD

**Issue by suguby** [IvanRyavkin/vovan#3]
Сделай класс, в котором методы будут одинаковыми с существующими функуциями. то есть
class Runner:
    def get_data(self, gile_name):
        ...
фкнция main тоже идет в класс
потом мы посмотрим, что это нам даст.

**Comment by IvanRyavkin** [comment]
Перенес все в класс  - работает
Дайте знать если я неправильно понял задание, или что то не так сделал
оффтоп: Когда планируется старт новой группы по django?

**Comment by suguby** [comment]
я подправил код, и дал указания по улучшению.
Для новой группы нужны еще 2-4 человека, есть у тебя знакомые? Другой претендент вот как набирает http://djbook.ru/forum/topic/4411/ :)
я не хотел рекламироваться, пока сайт не доделаю, но вы меня подвигаете

**Comment by suguby** [comment]
нашелся еще двое желающих :) так что минимальная группа собирается. Ты когда вована подправишь? после исправления нужно убирать строки # TODO

**Comment by IvanRyavkin** [comment]
Это отличная новость) когда планируется старт?
вована я почти подправил, застрял на атрибутах, читал, потом уезжал
я правильно понял что имеется ввиду data и file_name или нет?
 histogram, letters  у меня через self используются только в def print_result

**Comment by IvanRyavkin** [comment]
обновил код, посмотрите предыдущий комент по последней тудушке

**Comment by IvanRyavkin** [comment]
не нравится вот это место мне, можно как то проверить методами argrapse что запуск был без параметров?
```
if args.file_name:
            long_str = args.file_name.read().strip()
            return ''.join(long_str.split())
elif args.text:
            long_str = args.text.strip()
            return ''.join(long_str.split())
else:
            parser.print_help()
            sys.exit()
```
хотелось бы получить что то типо
```
if argparse все параметры None:
    parser.print_help()
    sys.exit()
if args.file_name:
            long_str = args.file_name.read().strip()
if args.text:
            long_str = args.text.strip()
return ''.join(long_str.split())
```

**Comment by suguby** [comment]
вполне нормальный подход. рассматривай это как аналог case of в паскале или switch case в С++. 
вначале перебираем все нужные варианты, если не нашлось - дефолтное действие.

**Comment by IvanRyavkin** [comment]
окей
